### ISSUE TITLE
iv-play does not work in Windows XP, can you build one version compatible with windows xp?

### ISSUE THREAD

**Issue by gfernval** [Mataniko/IV-Play#40]
You have to use .NET Framework 4.0, because .NET Framework 4.5 is not compatible with Windows XP

**Comment by retroarchgirl** [comment]
This is ONLY possible when you use an older version then Visual Studio 2022. 
Because we prefer to use latest version of Visual Studio and  Visual Studio 2022 can't target  .NET Framework 4.0, you can download an older version of Visual Studio and compile it by setting the framework to 4.0. No code changes would be required.

![afbeelding](https://user-images.githubusercontent.com/131728750/236073190-f278a667-dc91-463e-ac0e-39ae4c884bfc.png)

**Comment by john-iv** [comment]
Closed, not planned.
